#!/usr/bin/env bash
set -x
set -e

# FIXME: All of the following makes lots of assumptions, should be fixed later
LODEVICE=$(losetup -f)
losetup $LODEVICE *.img
partprobe $LODEVICE
mount "${LODEVICE}p1" /mnt
dd if="/mnt/usr/lib/linux-u-boot-rock64/idbloader.bin" of="${LODEVICE}" seek=64
dd if="/mnt/usr/lib/linux-u-boot-rock64/trust.bin" of="${LODEVICE}" seek=24576
dd if="/mnt/usr/lib/linux-u-boot-rock64/uboot.img" of="${LODEVICE}" seek=16384
umount /mnt
losetup -d $LODEVICE
