#!/usr/bin/env bash
set -x
set -e

# FIXME: All of the following makes lots of assumptions, should be fixed later
# LODEVICE=$(losetup -f)
# losetup $LODEVICE *.img
# partprobe $LODEVICE
# mount "${LODEVICE}p1" /mnt
RET=$(udisksctl loop-setup -f result/$RESULT --no-user-interaction)
LOOP=$(echo $RET | awk '{print $5;}' | sed -e 's/\.//g')
echo $LOOP
udisksctl mount -b $LOOP
MOUNTED=$(udisksctl info -b $LOOP | grep MountPoints | awk '{print $2;}')
echo $MOUNTED
dd if="/mnt/usr/lib/linux-u-boot-rock64/idbloader.img" of="${LOOP}" seek=64
udisksctl umount -b $LOOP
#losetup -d $LODEVICE
