#!/bin/sh

## live-config(7) - System Configuration Components
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


#set -e

Cmdline ()
{
	# Reading kernel command line
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.user-default-groups=*|user-default-groups=*)
				LIVE_USER_DEFAULT_GROUPS="${_PARAMETER#*user-default-groups=}"
				;;

			live-config.user-fullname=*|user-fullname=*)
				LIVE_USER_FULLNAME="${_PARAMETER#*user-fullname=}"
				;;

			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done
}

Init ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/user-setup.list ] || \
	   [ -e /var/lib/live/config/user-setup ]
	then
		exit 0
	fi

	echo -n " user-setup"
}

root_password () {
	if ! [ -e /etc/passwd ]; then
		return 1
	fi
	
	# Assume there is a root password if NIS is being used.
	if grep -q '^+:' /etc/passwd; then
		return 0
	fi

	# Be more careful than usual about test arguments in the following,
	# just in case (for example) the encrypted password string is "!".

	if [ -e /etc/shadow ] && \
	   [ -n "`grep ^root: /etc/shadow | cut -d : -f 2`" ] && \
	   [ "x`grep ^root: /etc/shadow | cut -d : -f 2`" != 'x*' ] && \
	   [ "x`grep ^root: /etc/shadow | cut -d : -f 2`" != 'x!*' ]; then
		return 0
	fi
	
	if [ -e /etc/passwd ] && \
		[ -n "`grep ^root: /etc/passwd | cut -d : -f 2`" ] && \
		[ "x`grep ^root: /etc/passwd | cut -d : -f 2`" != 'xx' ]; then
			return 0
	fi

	return 1
}

setpassword () {
	local USER PASSWD
	USER="$1"
	PASSWD="$2"
        usermod --password=$PASSWD $USER
}

Config ()
{
	# Checking if package is already configured differently
	if grep -q "^${LIVE_USERNAME}:" /etc/passwd
	then
		exit 0
	fi

	# Adjust formating of groups
	if [ -n "${LIVE_USER_DEFAULT_GROUPS}" ]
	then
		LIVE_USER_DEFAULT_GROUPS="$(echo ${LIVE_USER_DEFAULT_GROUPS} | sed -e 's|,| |g')"
	fi

	# Make sure user is not in sudo group if sudo is disabled
	case "${LIVE_CONFIG_NOROOT}" in
		true)
			LIVE_USER_DEFAULT_GROUPS="$(echo ${LIVE_USER_DEFAULT_GROUPS} | sed -e 's|sudo||')"
			;;
	esac

	# Default password is: live
	# passwords can be generated with 'echo "live" | mkpasswd -s',
	# a blank password is 'U6aMy0wojraho'.
	_PASSWORD="8Ab05sVQ4LLps"

        if ! root_password; then
           setpassword "root" "*" ;
        fi
        # Create user
        #adduser --disabled-password --gecos "$LIVE_USER_FULLNAME" --uid 1000 "$LIVE_USERNAME"
        echo "live:x:1000:1000:Debian Live user,,,:/home/live:/bin/bash" >> /etc/passwd
        echo "live:8Ab05sVQ4LLps:17595:0:99999:7:::" >> /etc/shadow
        echo "live:x:1000:" >> /etc/group
        setpassword "$LIVE_USERNAME" $_PASSWORD ;

        # Add user to sudo group
        adduser "$LIVE_USERNAME" sudo ;
        adduser "$LIVE_USERNAME" adm ;
        adduser "$LIVE_USERNAME" lpadmin   ;
        adduser "$LIVE_USERNAME" debian-tor ;
        #echo "$LIVE_USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
        
        mkdir -p /home/$LIVE_USERNAME/
        chown "$LIVE_USERNAME:$LIVE_USERNAME" "/home/$LIVE_USERNAME"
        cp -r /etc/skel/.* /home/$LIVE_USERNAME/
        cp -r /etc/skel/* /home/$LIVE_USERNAME/
        chown -R "$LIVE_USERNAME:$LIVE_USERNAME" "/home/$LIVE_USERNAME"
        
        

	# Creating state file
	touch /var/lib/live/config/user-setup
}

Cmdline
Init
Config
